apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  # +required Name of the component that this configuration belongs to.
  name:
  # +required Project name of the component that this component belongs to. Cannot be changed after creation.
  projectName: Test-Connections-Project
  annotations:
    componentType: Service
spec:
  # +optional Build instructions for the component.
  build:
    # +required Name of the branch. This is used to identify the corresponding deployment track.
    branch: main
  # +optional Incoming connection details for the component (AKA Endpoints).

  outbound:
    # +optional Defines the service references from the internal API marketplace.
    serviceReferences:
      # +required Name of the service reference
    - name: choreo:///hasithahiranya/kaqg/hxgwgp/803f0/v1.0/ORGANIZATION
      connectionConfig: 01ee7cc5-118e-13d0-b2ab-488af1c578f2
      env:
      - from: ServiceURL
        to: SERVICE_URL
      - from: ConsumerKey
        to: CLIENT_ID
      - from: ConsumerSecret
        to: CLIENT_SECRET
      - from: TokenURL
        to: TOKEN_URL
